name: Update CDN assets

on:
  schedule:
    - cron: "43 */6 * * *"
  workflow_dispatch:

jobs:
  publish:
    name: Update assets
    runs-on: ubuntu-latest
    steps:
      - name: Repo check
        run: |
          if [[ "$GITHUB_REPOSITORY_OWNER" != "uBlockOrigin" ]]; then
            echo "This GitHub Action is meant to deliver filter lists for uBO."
            echo "You shouldn't need to run this GitHub Action in your fork."
            echo "If you do, please customize the cron expression above, and"
            echo "the URLs below."
            exit 1
          fi
          exit 0
      - name: Clone uAssetsCDN
        uses: actions/checkout@v3
      - name: Generate version string
        run: |
          TAGNAME=$(date -u "+%Y.%-m.%-d.")$(date -u "+%H*60+%M" | bc)
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "Version string is $TAGNAME"
      - name: Copy shell script from uAssets
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=master https://github.com/uBlockOrigin/uAssets.git $TMPDIR
          cp -v $TMPDIR/tools/make-diffpatch.sh .
      - name: Copy uAssets/filters to uAssetsCDN
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=gh-pages https://github.com/uBlockOrigin/uAssets.git $TMPDIR
          cp -v $TMPDIR/filters/*.txt filters/
          cp -v $TMPDIR/thirdparties/*.txt thirdparties/
      - name: Copy uBlock/assets*.json to uAssetsCDN
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=master https://github.com/gorhill/uBlock.git $TMPDIR
          cp -v $TMPDIR/assets/assets*.json ublock/
      - name: Commit changes, if any
        run: |
          ./make-diffpatch.sh "${{ env.TAGNAME }}"
          if [[ -z $(git diff --name-only --cached) ]]; then exit 0; fi
          git config user.name "GitHub Actions: main"
          git config user.email "<>"
          git commit -m "Update modified CDN assets to ${{ env.TAGNAME }}"
          git push origin main
          git tag ${{ env.TAGNAME }}
          git push origin ${{ env.TAGNAME }}
