name: Update CDN assets

on:
  schedule:
    - cron: "43 */6 * * *"
  workflow_dispatch:

jobs:
  publish:
    name: Update assets
    runs-on: ubuntu-latest
    steps:
      - name: Repo check
        run: |
          if [[ "$GITHUB_REPOSITORY_OWNER" != "uBlockOrigin" ]]; then
            echo "This GitHub Action is meant to deliver filter lists for uBO."
            echo "You shouldn't need to run this GitHub Action in your fork."
            echo "If you do, please customize the cron expression above."
            exit 1
          fi
          exit 0
      - name: Clone uAssetsCDN
        uses: actions/checkout@v3
      - name: Copy uAssets/filters to uAssetsCDN
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=gh-pages https://github.com/uBlockOrigin/uAssets.git $TMPDIR
          cp -v $TMPDIR/filters/*.txt filters/
          cp -v $TMPDIR/thirdparties/*.txt thirdparties/
      - name: Copy uBlock/assets*.json to uAssetsCDN
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 https://github.com/gorhill/uBlock.git $TMPDIR
          cp -v $TMPDIR/assets/assets*.json ublock/
      - name: Commit changes, if any
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git add -u filters/ ublock/ thirdparties/
            git commit -m "Update all CDN assets"
            git push origin main
          fi
